update aoc script

diff --git a/2022/aoc b/2022/aoc
--- a/2022/aoc
+++ b/2022/aoc
@@ -1,27 +1,34 @@
 #!/bin/zsh
 
-CMD=$1
-DAY=$2
+DAY=$1
+SESSION=$(cat .session)
 
 if [ -z "$DAY" ]; then
-    DAY=$(ls | grep day | sort -r | head -n 1)
+    if [ $(date +%m%y) = "1222" ]; then
+        DAY="day$(date +%d)"
+        if [ ! -d "$DAY" ]; then
+            cp -R day00 "$DAY"
+            DAY_URL="https://adventofcode.com/2022/day/$(date +%e | xargs)"
+            echo "created ./$DAY"
+            if [ ! -z "$SESSION" ]; then
+                INPUT="$DAY/input.txt"
+                curl -fsSL --cookie session=$SESSION "$DAY_URL/input" > "$INPUT" && echo "input downloaded successfully"
+            fi
+            echo "happy solving $DAY_URL"
+            exit 0
+        fi
+    else
+        DAY=$(ls | grep day | sort -r | head -n 1)
+    fi
+else
+    if [ ! -d "$DAY" ]; then
+        echo "unable to find directory '$DAY'"
+        exit 1
+    fi
 fi
 
-if [ ! -d "$DAY" ]; then
-    echo "unable to find directory '$DAY'"
-    exit 1
-fi
-
-case $CMD in
-test)
-    echo "running tests for $DAY"
-    pipenv run python $DAY/solution.py
-    ;;
-run)
-    echo "running $DAY"
-    pipenv run python -m $DAY
-    ;;
-*)
-    echo "Usage: $0 [test|run] [optional: dir to use]"
-    exit 1
-esac
+echo "running $DAY"
+echo "-- tests ---"
+pipenv run python $DAY/solution.py
+echo "-- real deal ---"
+pipenv run python -m $DAY
